apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-microservice
  template:
    metadata:
      labels:
        app: db-microservice
    spec:
      containers:
        - name: db-microservice
          image: mongo:3.7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: $(MONGO_ROOT_USER)
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: $(MONGO_ROOT_PASSWORD)
            - name: MONGO_INITDB_DATABASE
              value: $(MONGO_DATABASE)
            - name: MONGO_USER
              value: $(MONGO_USER)
            - name: MONGO_PASSWORD
              value: $(MONGO_PASSWORD)
          volumeMounts:
            - name: db-microservice-data
              mountPath: /data/db
      volumes:
        - name: db-microservice-data
          emptyDir: {}
