apiVersion: apps/v1
kind: Deployment
metadata:
  name: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
        - name: event
          image: $(DOCKER_NAMESPACE)/event:latest
