apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
        - name: mailer
          image: $(DOCKER_NAMESPACE)/mailer:latest
