apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: $(DOCKER_NAMESPACE)/server:latest
          ports:
            - containerPort: 3000
          env:
            - name: BCRYPT_SALT
              value: $(BCRYPT_SALT_VALUE)
            - name: JWT_SECRET_KEY
              value: $(JWT_SECRET_KEY_VALUE)
            - name: JWT_EXPIRATION
              value: $(JWT_EXPIRATION_VALUE)
            - name: DB_URL
              value: postgres://$(DB_USER):$(DB_PASSWORD)@db:5432/$(DB_NAME)
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
