apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-admin
  template:
    metadata:
      labels:
        app: web-admin
    spec:
      containers:
        - name: web-admin
          image: $(DOCKER_NAMESPACE)/web-admin:latest
          ports:
            - containerPort: 3001
          env:
            - name: REACT_APP_SERVER_URL
              value: $(SERVER_URL)
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
