name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images - server
        uses: docker/build-push-action@v2
        with:
          context: ./apps/web
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/server:latest

      - name: Build and push Docker images - migrate
        uses: docker/build-push-action@v2
        with:
          context: ./apps/web
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/migrate:latest

      - name: Build and push Docker images - web-admin
        uses: docker/build-push-action@v2
        with:
          context: ./apps/web-admin
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/web-admin:latest

      - name: Build and push Docker images - gateway
        uses: docker/build-push-action@v2
        with:
          context: ./apps/analytics-app/gateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gateway:latest

      - name: Build and push Docker images - analytic
        uses: docker/build-push-action@v2
        with:
          context: ./apps/analytics-app/analytic
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/analytic:latest

      - name: Build and push Docker images - event
        uses: docker/build-push-action@v2
        with:
          context: ./apps/analytics-app/event
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/event:latest

      - name: Build and push Docker images - token
        uses: docker/build-push-action@v2
        with:
          context: ./apps/analytics-app/token
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/token:latest

      - name: Build and push Docker images - mailer
        uses: docker/build-push-action@v2
        with:
          context: ./apps/analytics-app/mailer
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mailer:latest

      - name: Build and push Docker images - permission
        uses: docker/build-push-action@v2
        with:
          context: ./apps/analytics-app/permission
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/permission:latest

      - name: Build and push Docker images - user
        uses: docker/build-push-action@v2
        with:
          context: ./apps/analytics-app/user
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user:latest

      - name: Build and push Docker images - frontend-analytics
        uses: docker/build-push-action@v2
        with:
          context: ./apps/analytics-app/front
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend-analytics:latest
