name: SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: debian
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22

      - name: Create Docker network
        run: docker network create infrastructure

      - name: Build Docker image
        run: docker build

      - name: Start Docker containers
        run: docker-compose up -d
